// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/alfariiizi/vandor/internal/infrastructure/db/clinicuser"
	"github.com/alfariiizi/vandor/internal/infrastructure/db/predicate"
)

// ClinicUserDelete is the builder for deleting a ClinicUser entity.
type ClinicUserDelete struct {
	config
	hooks    []Hook
	mutation *ClinicUserMutation
}

// Where appends a list predicates to the ClinicUserDelete builder.
func (cud *ClinicUserDelete) Where(ps ...predicate.ClinicUser) *ClinicUserDelete {
	cud.mutation.Where(ps...)
	return cud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cud *ClinicUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cud.sqlExec, cud.mutation, cud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cud *ClinicUserDelete) ExecX(ctx context.Context) int {
	n, err := cud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cud *ClinicUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clinicuser.Table, sqlgraph.NewFieldSpec(clinicuser.FieldID, field.TypeUUID))
	if ps := cud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cud.mutation.done = true
	return affected, err
}

// ClinicUserDeleteOne is the builder for deleting a single ClinicUser entity.
type ClinicUserDeleteOne struct {
	cud *ClinicUserDelete
}

// Where appends a list predicates to the ClinicUserDelete builder.
func (cudo *ClinicUserDeleteOne) Where(ps ...predicate.ClinicUser) *ClinicUserDeleteOne {
	cudo.cud.mutation.Where(ps...)
	return cudo
}

// Exec executes the deletion query.
func (cudo *ClinicUserDeleteOne) Exec(ctx context.Context) error {
	n, err := cudo.cud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clinicuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cudo *ClinicUserDeleteOne) ExecX(ctx context.Context) {
	if err := cudo.Exec(ctx); err != nil {
		panic(err)
	}
}
